services:
  - type: web
    name: ig-tracker-downloader-andremgsnake
    runtime: python
    plan: free
    region: frankfurt
    rootDir: backend
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app --bind 0.0.0.0:$PORT --workers 1 --threads 4 --timeout 180
    healthCheckPath: /health
    autoDeployTrigger: off
